"""Advanced SubStation Alpha ``.ass`` writer.

The format every video editor, karaoke tool and styling workflow expects
(Aegisub, libass, ffmpeg's ``subtitles=`` filter, VLC, mpv, Premiere,
Resolve). SRT carries text and timing; ASS carries *presentation* —
fonts, colours, positioning and per-syllable karaoke.

Two things this writer does that SRT and VTT cannot:

* **Karaoke.** When a segment has a ``words`` list, each word is emitted
  with a ``{\\kNN}`` tag whose duration highlights it as it is spoken.
  Word-level timings were previously only reachable through VTT's
  ``<c>`` cues, which almost nothing outside a browser reads.
* **Speaker in its own field.** ASS has a dedicated *Name* (actor)
  column, so a diarised transcript keeps its speaker labels as
  structured metadata instead of glued onto the front of the subtitle
  text where every downstream tool has to parse them back out.

Writing targets ASS (``ScriptType: v4.00+``) only. The parser in
``core.convert`` also accepts legacy SSA (v4.00), because old files exist
— but there is no reason to *produce* the legacy format.
"""
from __future__ import annotations

import math

from .base import normalize_text

#: Playback resolution the default style is designed against. Players
#: scale relative to this, so stating it keeps the subtitle the same
#: apparent size on a 720p and a 4K render instead of tiny on one of them.
PLAY_RES_X = 1920
PLAY_RES_Y = 1080

#: ``&HAABBGGRR`` — ASS colours are BGR with an INVERTED alpha byte
#: (00 = opaque). SecondaryColour is what a karaoke word looks like
#: *before* it is sung, so it has to differ from PrimaryColour or the
#: highlight is invisible.
_PRIMARY = "&H00FFFFFF"      # white — already sung / normal text
_SECONDARY = "&H0000FFFF"    # yellow — not yet sung
_OUTLINE = "&H00000000"      # black outline
_BACK = "&H80000000"         # semi-transparent black shadow

_SCRIPT_INFO = f"""[Script Info]
; Generated by Whisper Project
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: {PLAY_RES_X}
PlayResY: {PLAY_RES_Y}
"""

_STYLES = (
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
    "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
    "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
    "Alignment, MarginL, MarginR, MarginV, Encoding\n"
    f"Style: Default,Arial,54,{_PRIMARY},{_SECONDARY},{_OUTLINE},{_BACK},"
    "0,0,0,0,100,100,0,0,1,3,1,2,60,60,40,1\n"
)

_EVENTS_HEADER = (
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, "
    "MarginV, Effect, Text\n"
)


def fmt_ass_time(seconds: float) -> str:
    """ASS ``H:MM:SS.cc`` — one hour digit, centisecond precision.

    Not ``fmt_srt_time``: ASS uses a single (unpadded) hour field and two
    decimal places, and a player that meets ``00:00:01,500`` here will
    either drop the line or mis-time it.
    """
    if seconds is None or not isinstance(seconds, (int, float)):
        seconds = 0.0
    seconds = float(seconds)
    if not math.isfinite(seconds) or seconds < 0:
        seconds = 0.0
    total_cs = int(round(seconds * 100))
    hours, rem = divmod(total_cs, 360_000)
    minutes, rem = divmod(rem, 6_000)
    sec, cs = divmod(rem, 100)
    # ASS has no field wide enough for >9h; clamp rather than emit a
    # 2-digit hour that shifts every following field for strict parsers.
    hours = min(hours, 9)
    return f"{hours:d}:{minutes:02d}:{sec:02d}.{cs:02d}"


def escape_ass_text(text: str) -> str:
    """Make ``text`` safe inside an ASS Dialogue payload.

    ``{`` opens an override block, so an unescaped brace in the transcript
    silently swallows everything up to the next ``}``. Real newlines have
    to become the literal ``\\N`` marker, and a leading/trailing space is
    dropped by most renderers unless written as ``\\h``.
    """
    if not text:
        return ""
    out = str(text).replace("\\", "\\\\")
    out = out.replace("{", "\\{").replace("}", "\\}")
    out = out.replace("\r\n", "\n").replace("\r", "\n")
    out = out.replace("\n", "\\N")
    return out


def _speaker_name(seg: dict) -> str:
    """The ASS *Name* field — commas would shift every later field."""
    raw = seg.get("speaker") if isinstance(seg, dict) else None
    if raw in (None, ""):
        return ""
    return str(raw).strip().replace(",", ";")


def _karaoke_payload(seg: dict) -> str:
    """Per-word ``{\\kNN}`` payload, or plain escaped text without words.

    ``\\k`` durations are in centiseconds and are *relative* — each tag
    says how long its own word lasts — so they are derived from the gaps
    between word timings rather than from absolute positions. A gap
    between two words (a pause) is folded onto the front of the next word
    so the highlight does not run ahead of the voice.
    """
    words = seg.get("words") or []
    if not words:
        return escape_ass_text(normalize_text(seg.get("text", "")))

    try:
        seg_start = float(seg.get("start", 0.0))
    except (TypeError, ValueError):
        seg_start = 0.0

    parts: list[str] = []
    cursor = seg_start
    emitted = False
    for w in words:
        if not isinstance(w, dict):
            continue
        token = w.get("word")
        token = "" if token is None else str(token)
        token = token.strip()
        if not token:
            continue
        start = _coerce(w.get("start"), cursor)
        end = _coerce(w.get("end"), start)
        if end < start:
            end = start
        # Silence before this word belongs to this word's highlight.
        lead_cs = max(0, int(round((start - cursor) * 100)))
        dur_cs = max(1, int(round((end - start) * 100)))
        # Separate words with a real space BEFORE the tag, so the
        # highlight boundary lands between words rather than inside one.
        sep = " " if emitted else ""
        parts.append(f"{sep}{{\\k{lead_cs + dur_cs}}}{escape_ass_text(token)}")
        cursor = end
        emitted = True

    if not emitted:
        return escape_ass_text(normalize_text(seg.get("text", "")))
    return "".join(parts)


def _coerce(value: object, fallback: float) -> float:
    try:
        out = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return fallback
    return out if math.isfinite(out) else fallback


def write(segments: list[dict], audio_path: str = "") -> str:
    """Render ``segments`` as a complete ASS script."""
    out: list[str] = [_SCRIPT_INFO, "\n", _STYLES, "\n", _EVENTS_HEADER]
    for seg in segments or []:
        if not isinstance(seg, dict):
            continue
        try:
            start = float(seg.get("start", 0.0))
        except (TypeError, ValueError):
            start = 0.0
        try:
            end = float(seg.get("end", start))
        except (TypeError, ValueError):
            end = start
        if end < start:
            end = start
        payload = _karaoke_payload(seg)
        if not payload:
            continue
        out.append(
            "Dialogue: 0,"
            f"{fmt_ass_time(start)},{fmt_ass_time(end)},"
            f"Default,{_speaker_name(seg)},0,0,0,,{payload}\n"
        )
    return "".join(out)
