"""Real (tiny-model) transcription E2E — proves the actual pipeline works on macOS.

Unlike the hermetic unit suite (which mocks the model) and the heavy tests/smoke
suite (which needs the ~3 GB shipped model + a real video), this exercises the REAL
inference path — faster-whisper / CTranslate2 — plus the project's REAL output
writers, using only the ~75 MB ``tiny`` model and a short clip of genuine macOS
``say`` speech (generated by the CI workflow). It closes the "does transcription
actually run + produce output on Apple Silicon?" gap cheaply.

Usage:
    python tools/e2e_tiny_macos.py <clip.wav>

Exits non-zero on any failure.
"""
from __future__ import annotations

import os
import re
import sys
import tempfile


def main(wav: str) -> int:
    print(f"[e2e] platform={sys.platform} wav={wav} ({os.path.getsize(wav)} bytes)")

    # --- real inference (the default backend) -------------------------------
    from faster_whisper import WhisperModel

    model = WhisperModel("tiny", device="cpu", compute_type="int8")
    segments, info = model.transcribe(wav, language="en")
    segs = [
        {"start": float(s.start), "end": float(s.end), "text": s.text}
        for s in segments
    ]
    assert segs, "no segments produced — inference returned nothing"

    text = " ".join(s["text"] for s in segs).strip()
    print(f"[e2e] transcript: {text!r}")
    words = re.findall(r"[A-Za-z]+", text)
    assert len(words) >= 3, f"transcript too short / not real speech: {text!r}"
    hits = [w for w in ("quick", "brown", "fox", "jumps", "lazy", "dog", "box", "jugs")
            if w in text.lower()]
    print(f"[e2e] expected-word hits: {hits}")

    # --- the project's real output writers on real segments -----------------
    from core import writers as W

    out_dir = tempfile.mkdtemp(prefix="e2e_out_")
    for fmt in ("srt", "vtt", "json", "txt"):
        body = W.get_writer(fmt)(segs, wav)
        path = os.path.join(out_dir, "out." + fmt)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        size = os.path.getsize(path)
        assert size > 0, f"{fmt} writer produced an empty file"
        print(f"[e2e] wrote {fmt}: {size} bytes")

    print("[e2e] OK — real tiny-model transcription + project writers on", sys.platform)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python tools/e2e_tiny_macos.py <clip.wav>", file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1]))
